"""initial schema

Revision ID: c48cb54b4cd8
Revises: 
Create Date: 2026-05-12 10:33:16.821034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c48cb54b4cd8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('podcasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage_progress', sa.Float(), nullable=False),
    sa.Column('audio_path', sa.String(length=500), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('cost_cents', sa.Integer(), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ready_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_podcasts_user_created', 'podcasts', ['user_id', 'created_at'], unique=False)
    op.create_table('preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exclusions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('length_min', sa.Integer(), nullable=False),
    sa.Column('tone', sa.String(length=32), nullable=False),
    sa.Column('voice_id', sa.String(length=64), nullable=False),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('podcast_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcasts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_type_created', 'events', ['type', 'created_at'], unique=False)
    op.create_index('ix_events_user_created', 'events', ['user_id', 'created_at'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('podcast_id', sa.UUID(), nullable=False),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=2000), nullable=False),
    sa.Column('source_outlet', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_sec', sa.Float(), nullable=True),
    sa.Column('end_sec', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segments')
    op.drop_index('ix_events_user_created', table_name='events')
    op.drop_index('ix_events_type_created', table_name='events')
    op.drop_table('events')
    op.drop_table('preferences')
    op.drop_index('ix_podcasts_user_created', table_name='podcasts')
    op.drop_table('podcasts')
    op.drop_table('users')
    # ### end Alembic commands ###
